/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.ui.contentassist;

import org.eclipse.emf.henshin.text.ui.contentassist.AbstractHenshin_textProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Henshin_textProposalProvider extends AbstractHenshin_textProposalProvider {
}
