/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.scoping;

import org.eclipse.emf.henshin.text.scoping.AbstractHenshin_textScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Henshin_textScopeProvider extends AbstractHenshin_textScopeProvider {
}
