<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore2gen"
    nsURI="http://ecore2gen" nsPrefix="ecore2gen">
  <eClassifiers xsi:type="ecore:EClass" name="Marker">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mark" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecore" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genModel" eType="ecore:EClass http://www.eclipse.org/emf/2002/GenModel#//GenBase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
