/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Henshin_textStandaloneSetup extends Henshin_textStandaloneSetupGenerated {
  public static void doSetup() {
    new Henshin_textStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
