<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="philosophers"
    nsURI="http://www.eclipse.org/emf/2010/Henshin/Examples/Philosophers" nsPrefix="philosophers">
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plates" upperBound="-1"
        eType="#//Plate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="philosophers" upperBound="-1"
        eType="#//Philosopher" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forks" upperBound="-1"
        eType="#//Fork" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Philosopher" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forks" upperBound="-1"
        eType="#//Fork" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plate" eType="#//Plate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plate" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="forks" upperBound="-1"
        eType="#//Fork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork" eSuperTypes="#//Identifiable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
