/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.ui.outline;

import org.eclipse.emf.henshin.text.henshin_text.Attribute;
import org.eclipse.emf.henshin.text.henshin_text.Call;
import org.eclipse.emf.henshin.text.henshin_text.ConditionEdge;
import org.eclipse.emf.henshin.text.henshin_text.Conditions;
import org.eclipse.emf.henshin.text.henshin_text.Edges;
import org.eclipse.emf.henshin.text.henshin_text.Expression;
import org.eclipse.emf.henshin.text.henshin_text.Match;
import org.eclipse.emf.henshin.text.henshin_text.Parameter;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class Henshin_textOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final Attribute ele) {
    return true;
  }
  
  public boolean _isLeaf(final Match ele) {
    return true;
  }
  
  public boolean _isLeaf(final Parameter ele) {
    return true;
  }
  
  public boolean _isLeaf(final Conditions ele) {
    return true;
  }
  
  public boolean _isLeaf(final Edges ele) {
    return false;
  }
  
  public boolean _isLeaf(final ConditionEdge ele) {
    return false;
  }
  
  public boolean _isLeaf(final Expression ele) {
    return true;
  }
  
  public boolean _isLeaf(final Call ele) {
    return true;
  }
}
