<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="compactconditionmodel" nsURI="http://www.example.org/CompactConditionModel"
    nsPrefix="compactconditionmodel">
  <eClassifiers xsi:type="ecore:EClass" name="CompactConditionModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compactconditions" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.henshin.laxcondition/model/laxcondition.ecore#//Condition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeGraph" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
</ecore:EPackage>
