<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vehicles" nsURI="http://vehicles/1.0" nsPrefix="vehicles">
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" eType="#//Driver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//Person"
        eOpposite="#//Person/vehicleOwnership"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fleet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles" upperBound="-1"
        eType="#//Vehicle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MotorVehicle" eSuperTypes="#//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Driver" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicleOwnership" upperBound="-1"
        eType="#//Vehicle" eOpposite="#//Vehicle/owner"/>
  </eClassifiers>
</ecore:EPackage>
