/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.ui;

import com.google.inject.Injector;
import org.eclipse.emf.henshin.text.ui.internal.TextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Henshin_textExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TextActivator.getInstance().getInjector(TextActivator.ORG_ECLIPSE_EMF_HENSHIN_TEXT_HENSHIN_TEXT);
	}
	
}
