/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.emf.henshin.model.validation;

import org.eclipse.emf.henshin.model.Formula;

/**
 * A sample validator interface for {@link org.eclipse.emf.henshin.model.BinaryFormula}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BinaryFormulaValidator {
	boolean validate();

	boolean validateLeft(Formula value);
	boolean validateRight(Formula value);
}
