/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.emf.henshin.model.validation;

import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.henshin.model.Graph;
import org.eclipse.emf.henshin.model.Node;

/**
 * A sample validator interface for {@link org.eclipse.emf.henshin.model.Edge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EdgeValidator {
	boolean validate();

	boolean validateSource(Node value);
	boolean validateTarget(Node value);
	boolean validateType(EReference value);
	boolean validateGraph(Graph value);
}
