/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.emf.henshin.model.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.henshin.model.Edge;
import org.eclipse.emf.henshin.model.Formula;
import org.eclipse.emf.henshin.model.Node;

/**
 * A sample validator interface for {@link org.eclipse.emf.henshin.model.Graph}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GraphValidator {
	boolean validate();

	boolean validateNodes(EList<Node> value);
	boolean validateEdges(EList<Edge> value);
	boolean validateFormula(Formula value);
}
