/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.emf.henshin.model.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.henshin.model.Attribute;
import org.eclipse.emf.henshin.model.Edge;
import org.eclipse.emf.henshin.model.Graph;

/**
 * A sample validator interface for {@link org.eclipse.emf.henshin.model.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateType(EClass value);
	boolean validateAttributes(EList<Attribute> value);
	boolean validateGraph(Graph value);
	boolean validateIncoming(EList<Edge> value);
	boolean validateOutgoing(EList<Edge> value);
	boolean validateAllEdges(EList<Edge> value);
}
