/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.emf.henshin.model.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.henshin.model.Graph;
import org.eclipse.emf.henshin.model.Rule;
import org.eclipse.emf.henshin.model.TransformationUnit;

/**
 * A sample validator interface for {@link org.eclipse.emf.henshin.model.TransformationSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransformationSystemValidator {
	boolean validate();

	boolean validateRules(EList<Rule> value);
	boolean validateImports(EList<EPackage> value);
	boolean validateInstances(EList<Graph> value);
	boolean validateTransformationUnits(EList<TransformationUnit> value);
}
