<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="henshin"
    nsURI="http://www.eclipse.org/emf/2010/Henshin" nsPrefix="henshin">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescribedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationSystem" eSuperTypes="#//DescribedElement #//NamedElement">
    <eOperations name="findRuleByName" eType="#//Rule">
      <eParameters name="ruleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true" eOpposite="#//Rule/transformationSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//Transformation" containment="true" eOpposite="#//Transformation/transformationSystem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Graph" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//DescribedElement #//NamedElement #//TransformationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" lowerBound="1" eType="#//Graph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" lowerBound="1" eType="#//Graph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeConditions" upperBound="-1"
        eType="#//AttributeCondition" containment="true" eOpposite="#//AttributeCondition/rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//Mapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationSystem" lowerBound="1"
        eType="#//TransformationSystem" eOpposite="#//TransformationSystem/rules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true" eOpposite="#//Variable/rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeCondition" eSuperTypes="#//DescribedElement #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule" eOpposite="#//Rule/attributeConditions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditionText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//DescribedElement #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Rule" eOpposite="#//Rule/variables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//DescribedElement #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//PortKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//TransformationUnit"
        eOpposite="#//TransformationUnit/ports"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortObject" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortParameter" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//NamedElement">
    <eOperations name="removeEdge">
      <eParameters name="edge" lowerBound="1" eType="#//Edge"/>
    </eOperations>
    <eOperations name="removeNode">
      <eParameters name="node" eType="#//Node"/>
    </eOperations>
    <eOperations name="getContainerRule" eType="#//Rule"/>
    <eOperations name="findNodesByType" ordered="false" upperBound="-1" eType="#//Node">
      <eParameters name="nodeType" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eOperations name="findEdgesByType" ordered="false" upperBound="-1" eType="#//Edge">
      <eParameters name="edgeType" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" containment="true" eOpposite="#//Edge/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" eType="#//Formula"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphElement" abstract="true" interface="true">
    <eOperations name="getGraph" eType="#//Graph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="image" lowerBound="1" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//NamedElement #//GraphElement">
    <eOperations name="findOutgoingEdgesByType" ordered="false" upperBound="-1" eType="#//Edge">
      <eParameters name="edgeType" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    </eOperations>
    <eOperations name="findIncomingEdgesByType" ordered="false" upperBound="-1" eType="#//Edge">
      <eParameters name="edgeType" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    </eOperations>
    <eOperations name="findAttributeByType" eType="#//Attribute">
      <eParameters name="attributeType" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    </eOperations>
    <eOperations name="findOutgoingEdgeByType" eType="#//Edge">
      <eParameters name="targetNode" lowerBound="1" eType="#//Node"/>
      <eParameters name="edgeType" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    </eOperations>
    <eOperations name="findIncomingEdgeByType" eType="#//Edge">
      <eParameters name="sourceNode" lowerBound="1" eType="#//Node"/>
      <eParameters name="edgeType" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true" eOpposite="#//Attribute/node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//Graph"
        eOpposite="#//Graph/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allEdges" ordered="false"
        upperBound="-1" eType="#//Edge" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eOperations name="containsVariableByRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="rule" lowerBound="1" eType="#//Rule"/>
    </eOperations>
    <eOperations name="containsVariable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="variable" lowerBound="1" eType="#//Variable"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="#//Node"
        eOpposite="#//Node/attributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//GraphElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" lowerBound="1" eType="#//Graph"
        eOpposite="#//Graph/edges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" eSuperTypes="#//DescribedElement #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainUnit" lowerBound="1"
        eType="#//TransformationUnit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationSystem" lowerBound="1"
        eType="#//TransformationSystem" eOpposite="#//TransformationSystem/transformations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationUnit" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//Port" containment="true" eOpposite="#//Port/unit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portMappings" upperBound="-1"
        eType="#//PortMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentUnit" eSuperTypes="#//TransformationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subUnits" upperBound="-1"
        eType="#//TransformationUnit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequentialUnit" eSuperTypes="#//TransformationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subUnits" upperBound="-1"
        eType="#//TransformationUnit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalUnit" eSuperTypes="#//TransformationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="if" lowerBound="1" eType="#//TransformationUnit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1" eType="#//TransformationUnit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//TransformationUnit"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PriorityUnit" eSuperTypes="#//TransformationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subUnits" upperBound="-1"
        eType="#//TransformationUnit" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmalgamatedUnit" eSuperTypes="#//TransformationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="kernelRule" eType="#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiRules" upperBound="-1"
        eType="#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhsMappings" upperBound="-1"
        eType="#//Mapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhsMappings" upperBound="-1"
        eType="#//Mapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CountedUnit" eSuperTypes="#//TransformationUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subUnit" lowerBound="1"
        eType="#//TransformationUnit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedCondition" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conclusion" eType="#//Graph"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//Mapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Formula" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryFormula" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Formula"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryFormula" eSuperTypes="#//Formula">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Formula"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Formula"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//BinaryFormula"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//BinaryFormula"/>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//UnaryFormula"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PortKind">
    <eLiterals name="INPUT"/>
    <eLiterals name="OUTPUT" value="1"/>
    <eLiterals name="INPUT_OUTPUT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Port"/>
  </eClassifiers>
</ecore:EPackage>
