/*******************************************************************************
 * Copyright (c) 2010 CWI Amsterdam, Technical University Berlin, 
 * Philipps-University Marburg and others. All rights reserved.
 * This program and the accompanying materials are made 
 * available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     CWI Amsterdam - initial API and implementation
 *******************************************************************************/
package org.eclipse.emf.henshin.diagram.edit.parts;

import org.eclipse.draw2d.Connection;
import org.eclipse.draw2d.ConnectionLocator;
import org.eclipse.draw2d.geometry.Point;

/**
 * Link label locator class (not generated by GMF). 
 * 
 * @author Christian Krause
 */
public class LinkLabelLocator extends ConnectionLocator {
	
	// Distance from the mid point.
	private int distance;

	public LinkLabelLocator(Connection connection, int distance) {
		super(connection);
		this.distance = distance;
	}

	/*
	 * (non-Javadoc)
	 * @see org.eclipse.draw2d.ConnectionLocator#getReferencePoint()
	 */
	@Override
	protected Point getReferencePoint() {
		Connection connection = getConnection();
		Point p = connection.getPoints().getMidpoint();
		connection.translateToAbsolute(p);
		p.y += distance;
		return p;
	}

}
