<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="railcab"
    nsURI="http://hpi.uni-potsdam.de/railcab" nsPrefix="railcab">
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks" upperBound="-1"
        eType="#//Track" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles" upperBound="-1"
        eType="#//Vehicle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="convoys" upperBound="-1"
        eType="#//Convoy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Track">
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//Track"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shuttle" eSuperTypes="#//Vehicle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Convoy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shuttles" upperBound="-1"
        eType="#//Shuttle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="onTrack" eType="#//Track"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Train" eSuperTypes="#//Vehicle"/>
</ecore:EPackage>
