/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.eclipse.emf.henshin.text.henshin_text.Expression;
import org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage;
import org.eclipse.emf.henshin.text.henshin_text.IteratedUnit;
import org.eclipse.emf.henshin.text.henshin_text.UnitElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Iterated Unit</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.impl.IteratedUnitImpl#getIterations <em>Iterations</em>}</li>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.impl.IteratedUnitImpl#getSubElement <em>Sub Element</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IteratedUnitImpl extends UnitElementImpl implements IteratedUnit
{
  /**
   * The cached value of the '{@link #getIterations() <em>Iterations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIterations()
   * @generated
   * @ordered
   */
  protected Expression iterations;

  /**
   * The cached value of the '{@link #getSubElement() <em>Sub Element</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubElement()
   * @generated
   * @ordered
   */
  protected EList<UnitElement> subElement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IteratedUnitImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Henshin_textPackage.Literals.ITERATED_UNIT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getIterations()
  {
    return iterations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIterations(Expression newIterations, NotificationChain msgs)
  {
    Expression oldIterations = iterations;
    iterations = newIterations;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Henshin_textPackage.ITERATED_UNIT__ITERATIONS, oldIterations, newIterations);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIterations(Expression newIterations)
  {
    if (newIterations != iterations)
    {
      NotificationChain msgs = null;
      if (iterations != null)
        msgs = ((InternalEObject)iterations).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Henshin_textPackage.ITERATED_UNIT__ITERATIONS, null, msgs);
      if (newIterations != null)
        msgs = ((InternalEObject)newIterations).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Henshin_textPackage.ITERATED_UNIT__ITERATIONS, null, msgs);
      msgs = basicSetIterations(newIterations, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Henshin_textPackage.ITERATED_UNIT__ITERATIONS, newIterations, newIterations));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<UnitElement> getSubElement()
  {
    if (subElement == null)
    {
      subElement = new EObjectContainmentEList<UnitElement>(UnitElement.class, this, Henshin_textPackage.ITERATED_UNIT__SUB_ELEMENT);
    }
    return subElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Henshin_textPackage.ITERATED_UNIT__ITERATIONS:
        return basicSetIterations(null, msgs);
      case Henshin_textPackage.ITERATED_UNIT__SUB_ELEMENT:
        return ((InternalEList<?>)getSubElement()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Henshin_textPackage.ITERATED_UNIT__ITERATIONS:
        return getIterations();
      case Henshin_textPackage.ITERATED_UNIT__SUB_ELEMENT:
        return getSubElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Henshin_textPackage.ITERATED_UNIT__ITERATIONS:
        setIterations((Expression)newValue);
        return;
      case Henshin_textPackage.ITERATED_UNIT__SUB_ELEMENT:
        getSubElement().clear();
        getSubElement().addAll((Collection<? extends UnitElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Henshin_textPackage.ITERATED_UNIT__ITERATIONS:
        setIterations((Expression)null);
        return;
      case Henshin_textPackage.ITERATED_UNIT__SUB_ELEMENT:
        getSubElement().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Henshin_textPackage.ITERATED_UNIT__ITERATIONS:
        return iterations != null;
      case Henshin_textPackage.ITERATED_UNIT__SUB_ELEMENT:
        return subElement != null && !subElement.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //IteratedUnitImpl
