/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage;
import org.eclipse.emf.henshin.text.henshin_text.RuleNodeTypes;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rule Node Types</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RuleNodeTypesImpl extends MinimalEObjectImpl.Container implements RuleNodeTypes
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RuleNodeTypesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Henshin_textPackage.Literals.RULE_NODE_TYPES;
  }

} //RuleNodeTypesImpl
