/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage;
import org.eclipse.emf.henshin.text.henshin_text.SequentialProperties;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sequential Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SequentialPropertiesImpl extends UnitElementImpl implements SequentialProperties
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SequentialPropertiesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Henshin_textPackage.Literals.SEQUENTIAL_PROPERTIES;
  }

} //SequentialPropertiesImpl
