/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AND</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.AND#getLeft <em>Left</em>}</li>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.AND#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getAND()
 * @model
 * @generated
 */
public interface AND extends Logic
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Logic)
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getAND_Left()
   * @model containment="true"
   * @generated
   */
  Logic getLeft();

  /**
   * Sets the value of the '{@link org.eclipse.emf.henshin.text.henshin_text.AND#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Logic value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Logic)
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getAND_Right()
   * @model containment="true"
   * @generated
   */
  Logic getRight();

  /**
   * Sets the value of the '{@link org.eclipse.emf.henshin.text.henshin_text.AND#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Logic value);

} // AND
