/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition Edge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.ConditionEdge#getSource <em>Source</em>}</li>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.ConditionEdge#getTarget <em>Target</em>}</li>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.ConditionEdge#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getConditionEdge()
 * @model
 * @generated
 */
public interface ConditionEdge extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Source</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(ConditionNodeTypes)
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getConditionEdge_Source()
   * @model
   * @generated
   */
  ConditionNodeTypes getSource();

  /**
   * Sets the value of the '{@link org.eclipse.emf.henshin.text.henshin_text.ConditionEdge#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(ConditionNodeTypes value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(ConditionNodeTypes)
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getConditionEdge_Target()
   * @model
   * @generated
   */
  ConditionNodeTypes getTarget();

  /**
   * Sets the value of the '{@link org.eclipse.emf.henshin.text.henshin_text.ConditionEdge#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(ConditionNodeTypes value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(EReference)
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getConditionEdge_Type()
   * @model
   * @generated
   */
  EReference getType();

  /**
   * Sets the value of the '{@link org.eclipse.emf.henshin.text.henshin_text.ConditionEdge#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(EReference value);

} // ConditionEdge
