/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.Formula#getFormula <em>Formula</em>}</li>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.Formula#getConditionGraphs <em>Condition Graphs</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getFormula()
 * @model
 * @generated
 */
public interface Formula extends GraphElements, ConditionGraphElements
{
  /**
   * Returns the value of the '<em><b>Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Formula</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formula</em>' containment reference.
   * @see #setFormula(Logic)
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getFormula_Formula()
   * @model containment="true"
   * @generated
   */
  Logic getFormula();

  /**
   * Sets the value of the '{@link org.eclipse.emf.henshin.text.henshin_text.Formula#getFormula <em>Formula</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Formula</em>' containment reference.
   * @see #getFormula()
   * @generated
   */
  void setFormula(Logic value);

  /**
   * Returns the value of the '<em><b>Condition Graphs</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.henshin.text.henshin_text.ConditionGraph}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition Graphs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Graphs</em>' containment reference list.
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getFormula_ConditionGraphs()
   * @model containment="true"
   * @generated
   */
  EList<ConditionGraph> getConditionGraphs();

} // Formula
