/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Independent Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.IndependentUnit#getListOfLists <em>List Of Lists</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getIndependentUnit()
 * @model
 * @generated
 */
public interface IndependentUnit extends UnitElement
{
  /**
   * Returns the value of the '<em><b>List Of Lists</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.henshin.text.henshin_text.List}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List Of Lists</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Of Lists</em>' containment reference list.
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getIndependentUnit_ListOfLists()
   * @model containment="true"
   * @generated
   */
  EList<List> getListOfLists();

} // IndependentUnit
