/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Injective Matching</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.InjectiveMatching#isInjectiveMatching <em>Injective Matching</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getInjectiveMatching()
 * @model
 * @generated
 */
public interface InjectiveMatching extends RuleElement
{
  /**
   * Returns the value of the '<em><b>Injective Matching</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Injective Matching</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Injective Matching</em>' attribute.
   * @see #setInjectiveMatching(boolean)
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getInjectiveMatching_InjectiveMatching()
   * @model
   * @generated
   */
  boolean isInjectiveMatching();

  /**
   * Sets the value of the '{@link org.eclipse.emf.henshin.text.henshin_text.InjectiveMatching#isInjectiveMatching <em>Injective Matching</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Injective Matching</em>' attribute.
   * @see #isInjectiveMatching()
   * @generated
   */
  void setInjectiveMatching(boolean value);

} // InjectiveMatching
