/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multi Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.MultiRule#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.MultiRule#getMultiruleElements <em>Multirule Elements</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getMultiRule()
 * @model
 * @generated
 */
public interface MultiRule extends GraphElements
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getMultiRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.eclipse.emf.henshin.text.henshin_text.MultiRule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Multirule Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.henshin.text.henshin_text.RuleElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Multirule Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multirule Elements</em>' containment reference list.
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getMultiRule_MultiruleElements()
   * @model containment="true"
   * @generated
   */
  EList<RuleElement> getMultiruleElements();

} // MultiRule
