/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rollback</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.Rollback#isRollback <em>Rollback</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getRollback()
 * @model
 * @generated
 */
public interface Rollback extends SequentialProperties
{
  /**
   * Returns the value of the '<em><b>Rollback</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rollback</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rollback</em>' attribute.
   * @see #setRollback(boolean)
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getRollback_Rollback()
   * @model
   * @generated
   */
  boolean isRollback();

  /**
   * Sets the value of the '{@link org.eclipse.emf.henshin.text.henshin_text.Rollback#isRollback <em>Rollback</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rollback</em>' attribute.
   * @see #isRollback()
   * @generated
   */
  void setRollback(boolean value);

} // Rollback
