/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sequential Properties</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getSequentialProperties()
 * @model
 * @generated
 */
public interface SequentialProperties extends UnitElement
{
} // SequentialProperties
