/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getType()
 * @model
 * @generated
 */
public enum Type implements Enumerator
{
  /**
   * The '<em><b>EBig Decimal</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EBIG_DECIMAL_VALUE
   * @generated
   * @ordered
   */
  EBIG_DECIMAL(0, "eBigDecimal", "EBigDecimal"),

  /**
   * The '<em><b>EBig Integer</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EBIG_INTEGER_VALUE
   * @generated
   * @ordered
   */
  EBIG_INTEGER(1, "eBigInteger", "EBigInteger"),

  /**
   * The '<em><b>EBoolean</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EBOOLEAN_VALUE
   * @generated
   * @ordered
   */
  EBOOLEAN(2, "eBoolean", "EBoolean"),

  /**
   * The '<em><b>EBoolean Object</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EBOOLEAN_OBJECT_VALUE
   * @generated
   * @ordered
   */
  EBOOLEAN_OBJECT(3, "eBooleanObject", "EBooleanObject"),

  /**
   * The '<em><b>EByte</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EBYTE_VALUE
   * @generated
   * @ordered
   */
  EBYTE(4, "eByte", "EByte"),

  /**
   * The '<em><b>EByte Array</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EBYTE_ARRAY_VALUE
   * @generated
   * @ordered
   */
  EBYTE_ARRAY(5, "eByteArray", "EByteArray"),

  /**
   * The '<em><b>EByte Object</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EBYTE_OBJECT_VALUE
   * @generated
   * @ordered
   */
  EBYTE_OBJECT(6, "eByteObject", "EByteObject"),

  /**
   * The '<em><b>EChar</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ECHAR_VALUE
   * @generated
   * @ordered
   */
  ECHAR(7, "eChar", "EChar"),

  /**
   * The '<em><b>ECharacter Object</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ECHARACTER_OBJECT_VALUE
   * @generated
   * @ordered
   */
  ECHARACTER_OBJECT(8, "eCharacterObject", "ECharacterObject"),

  /**
   * The '<em><b>EDate</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EDATE_VALUE
   * @generated
   * @ordered
   */
  EDATE(9, "eDate", "EDate"),

  /**
   * The '<em><b>EDiagnostic Chain</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EDIAGNOSTIC_CHAIN_VALUE
   * @generated
   * @ordered
   */
  EDIAGNOSTIC_CHAIN(10, "eDiagnosticChain", "EDiagnosticChain"),

  /**
   * The '<em><b>EDouble</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EDOUBLE_VALUE
   * @generated
   * @ordered
   */
  EDOUBLE(11, "eDouble", "EDouble"),

  /**
   * The '<em><b>EDouble Object</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EDOUBLE_OBJECT_VALUE
   * @generated
   * @ordered
   */
  EDOUBLE_OBJECT(12, "eDoubleObject", "EDoubleObject"),

  /**
   * The '<em><b>EE List</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EE_LIST_VALUE
   * @generated
   * @ordered
   */
  EE_LIST(13, "eEList", "EEList"),

  /**
   * The '<em><b>EEnumerator</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EENUMERATOR_VALUE
   * @generated
   * @ordered
   */
  EENUMERATOR(14, "eEnumerator", "EEnumerator"),

  /**
   * The '<em><b>EFeature Map</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EFEATURE_MAP_VALUE
   * @generated
   * @ordered
   */
  EFEATURE_MAP(15, "eFeatureMap", "EFeatureMap"),

  /**
   * The '<em><b>EFeature Map Entry</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EFEATURE_MAP_ENTRY_VALUE
   * @generated
   * @ordered
   */
  EFEATURE_MAP_ENTRY(16, "eFeatureMapEntry", "EFeatureMapEntry"),

  /**
   * The '<em><b>EFloat</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EFLOAT_VALUE
   * @generated
   * @ordered
   */
  EFLOAT(17, "eFloat", "EFloat"),

  /**
   * The '<em><b>EFloat Object</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EFLOAT_OBJECT_VALUE
   * @generated
   * @ordered
   */
  EFLOAT_OBJECT(18, "eFloatObject", "EFloatObject"),

  /**
   * The '<em><b>EInt</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EINT_VALUE
   * @generated
   * @ordered
   */
  EINT(19, "eInt", "EInt"),

  /**
   * The '<em><b>EInteger Object</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EINTEGER_OBJECT_VALUE
   * @generated
   * @ordered
   */
  EINTEGER_OBJECT(20, "eIntegerObject", "EIntegerObject"),

  /**
   * The '<em><b>ETree Iterator</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ETREE_ITERATOR_VALUE
   * @generated
   * @ordered
   */
  ETREE_ITERATOR(21, "eTreeIterator", "ETreeIterator"),

  /**
   * The '<em><b>EInvocation Target Exception</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EINVOCATION_TARGET_EXCEPTION_VALUE
   * @generated
   * @ordered
   */
  EINVOCATION_TARGET_EXCEPTION(22, "eInvocationTargetException", "EInvocationTargetException"),

  /**
   * The '<em><b>EJava Class</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EJAVA_CLASS_VALUE
   * @generated
   * @ordered
   */
  EJAVA_CLASS(23, "eJavaClass", "EJavaClass"),

  /**
   * The '<em><b>EJava Object</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EJAVA_OBJECT_VALUE
   * @generated
   * @ordered
   */
  EJAVA_OBJECT(24, "eJavaObject", "EJavaObject"),

  /**
   * The '<em><b>ELong</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELONG_VALUE
   * @generated
   * @ordered
   */
  ELONG(25, "eLong", "ELong"),

  /**
   * The '<em><b>ELong Object</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELONG_OBJECT_VALUE
   * @generated
   * @ordered
   */
  ELONG_OBJECT(26, "eLongObject", "ELongObject"),

  /**
   * The '<em><b>EMap</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EMAP_VALUE
   * @generated
   * @ordered
   */
  EMAP(27, "eMap", "EMap"),

  /**
   * The '<em><b>EResource</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ERESOURCE_VALUE
   * @generated
   * @ordered
   */
  ERESOURCE(28, "eResource", "EResource"),

  /**
   * The '<em><b>EResource Set</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ERESOURCE_SET_VALUE
   * @generated
   * @ordered
   */
  ERESOURCE_SET(29, "eResourceSet", "EResourceSet"),

  /**
   * The '<em><b>EShort</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ESHORT_VALUE
   * @generated
   * @ordered
   */
  ESHORT(30, "eShort", "EShort"),

  /**
   * The '<em><b>EShort Object</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ESHORT_OBJECT_VALUE
   * @generated
   * @ordered
   */
  ESHORT_OBJECT(31, "eShortObject", "EShortObject"),

  /**
   * The '<em><b>EString</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ESTRING_VALUE
   * @generated
   * @ordered
   */
  ESTRING(32, "eString", "EString");

  /**
   * The '<em><b>EBig Decimal</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EBig Decimal</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EBIG_DECIMAL
   * @model name="eBigDecimal" literal="EBigDecimal"
   * @generated
   * @ordered
   */
  public static final int EBIG_DECIMAL_VALUE = 0;

  /**
   * The '<em><b>EBig Integer</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EBig Integer</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EBIG_INTEGER
   * @model name="eBigInteger" literal="EBigInteger"
   * @generated
   * @ordered
   */
  public static final int EBIG_INTEGER_VALUE = 1;

  /**
   * The '<em><b>EBoolean</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EBoolean</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EBOOLEAN
   * @model name="eBoolean" literal="EBoolean"
   * @generated
   * @ordered
   */
  public static final int EBOOLEAN_VALUE = 2;

  /**
   * The '<em><b>EBoolean Object</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EBoolean Object</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EBOOLEAN_OBJECT
   * @model name="eBooleanObject" literal="EBooleanObject"
   * @generated
   * @ordered
   */
  public static final int EBOOLEAN_OBJECT_VALUE = 3;

  /**
   * The '<em><b>EByte</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EByte</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EBYTE
   * @model name="eByte" literal="EByte"
   * @generated
   * @ordered
   */
  public static final int EBYTE_VALUE = 4;

  /**
   * The '<em><b>EByte Array</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EByte Array</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EBYTE_ARRAY
   * @model name="eByteArray" literal="EByteArray"
   * @generated
   * @ordered
   */
  public static final int EBYTE_ARRAY_VALUE = 5;

  /**
   * The '<em><b>EByte Object</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EByte Object</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EBYTE_OBJECT
   * @model name="eByteObject" literal="EByteObject"
   * @generated
   * @ordered
   */
  public static final int EBYTE_OBJECT_VALUE = 6;

  /**
   * The '<em><b>EChar</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EChar</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ECHAR
   * @model name="eChar" literal="EChar"
   * @generated
   * @ordered
   */
  public static final int ECHAR_VALUE = 7;

  /**
   * The '<em><b>ECharacter Object</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ECharacter Object</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ECHARACTER_OBJECT
   * @model name="eCharacterObject" literal="ECharacterObject"
   * @generated
   * @ordered
   */
  public static final int ECHARACTER_OBJECT_VALUE = 8;

  /**
   * The '<em><b>EDate</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EDate</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EDATE
   * @model name="eDate" literal="EDate"
   * @generated
   * @ordered
   */
  public static final int EDATE_VALUE = 9;

  /**
   * The '<em><b>EDiagnostic Chain</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EDiagnostic Chain</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EDIAGNOSTIC_CHAIN
   * @model name="eDiagnosticChain" literal="EDiagnosticChain"
   * @generated
   * @ordered
   */
  public static final int EDIAGNOSTIC_CHAIN_VALUE = 10;

  /**
   * The '<em><b>EDouble</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EDouble</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EDOUBLE
   * @model name="eDouble" literal="EDouble"
   * @generated
   * @ordered
   */
  public static final int EDOUBLE_VALUE = 11;

  /**
   * The '<em><b>EDouble Object</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EDouble Object</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EDOUBLE_OBJECT
   * @model name="eDoubleObject" literal="EDoubleObject"
   * @generated
   * @ordered
   */
  public static final int EDOUBLE_OBJECT_VALUE = 12;

  /**
   * The '<em><b>EE List</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EE List</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EE_LIST
   * @model name="eEList" literal="EEList"
   * @generated
   * @ordered
   */
  public static final int EE_LIST_VALUE = 13;

  /**
   * The '<em><b>EEnumerator</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EEnumerator</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EENUMERATOR
   * @model name="eEnumerator" literal="EEnumerator"
   * @generated
   * @ordered
   */
  public static final int EENUMERATOR_VALUE = 14;

  /**
   * The '<em><b>EFeature Map</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EFeature Map</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EFEATURE_MAP
   * @model name="eFeatureMap" literal="EFeatureMap"
   * @generated
   * @ordered
   */
  public static final int EFEATURE_MAP_VALUE = 15;

  /**
   * The '<em><b>EFeature Map Entry</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EFeature Map Entry</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EFEATURE_MAP_ENTRY
   * @model name="eFeatureMapEntry" literal="EFeatureMapEntry"
   * @generated
   * @ordered
   */
  public static final int EFEATURE_MAP_ENTRY_VALUE = 16;

  /**
   * The '<em><b>EFloat</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EFloat</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EFLOAT
   * @model name="eFloat" literal="EFloat"
   * @generated
   * @ordered
   */
  public static final int EFLOAT_VALUE = 17;

  /**
   * The '<em><b>EFloat Object</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EFloat Object</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EFLOAT_OBJECT
   * @model name="eFloatObject" literal="EFloatObject"
   * @generated
   * @ordered
   */
  public static final int EFLOAT_OBJECT_VALUE = 18;

  /**
   * The '<em><b>EInt</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EInt</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EINT
   * @model name="eInt" literal="EInt"
   * @generated
   * @ordered
   */
  public static final int EINT_VALUE = 19;

  /**
   * The '<em><b>EInteger Object</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EInteger Object</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EINTEGER_OBJECT
   * @model name="eIntegerObject" literal="EIntegerObject"
   * @generated
   * @ordered
   */
  public static final int EINTEGER_OBJECT_VALUE = 20;

  /**
   * The '<em><b>ETree Iterator</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ETree Iterator</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ETREE_ITERATOR
   * @model name="eTreeIterator" literal="ETreeIterator"
   * @generated
   * @ordered
   */
  public static final int ETREE_ITERATOR_VALUE = 21;

  /**
   * The '<em><b>EInvocation Target Exception</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EInvocation Target Exception</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EINVOCATION_TARGET_EXCEPTION
   * @model name="eInvocationTargetException" literal="EInvocationTargetException"
   * @generated
   * @ordered
   */
  public static final int EINVOCATION_TARGET_EXCEPTION_VALUE = 22;

  /**
   * The '<em><b>EJava Class</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EJava Class</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EJAVA_CLASS
   * @model name="eJavaClass" literal="EJavaClass"
   * @generated
   * @ordered
   */
  public static final int EJAVA_CLASS_VALUE = 23;

  /**
   * The '<em><b>EJava Object</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EJava Object</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EJAVA_OBJECT
   * @model name="eJavaObject" literal="EJavaObject"
   * @generated
   * @ordered
   */
  public static final int EJAVA_OBJECT_VALUE = 24;

  /**
   * The '<em><b>ELong</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ELong</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ELONG
   * @model name="eLong" literal="ELong"
   * @generated
   * @ordered
   */
  public static final int ELONG_VALUE = 25;

  /**
   * The '<em><b>ELong Object</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ELong Object</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ELONG_OBJECT
   * @model name="eLongObject" literal="ELongObject"
   * @generated
   * @ordered
   */
  public static final int ELONG_OBJECT_VALUE = 26;

  /**
   * The '<em><b>EMap</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EMap</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EMAP
   * @model name="eMap" literal="EMap"
   * @generated
   * @ordered
   */
  public static final int EMAP_VALUE = 27;

  /**
   * The '<em><b>EResource</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EResource</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ERESOURCE
   * @model name="eResource" literal="EResource"
   * @generated
   * @ordered
   */
  public static final int ERESOURCE_VALUE = 28;

  /**
   * The '<em><b>EResource Set</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EResource Set</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ERESOURCE_SET
   * @model name="eResourceSet" literal="EResourceSet"
   * @generated
   * @ordered
   */
  public static final int ERESOURCE_SET_VALUE = 29;

  /**
   * The '<em><b>EShort</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EShort</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ESHORT
   * @model name="eShort" literal="EShort"
   * @generated
   * @ordered
   */
  public static final int ESHORT_VALUE = 30;

  /**
   * The '<em><b>EShort Object</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EShort Object</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ESHORT_OBJECT
   * @model name="eShortObject" literal="EShortObject"
   * @generated
   * @ordered
   */
  public static final int ESHORT_OBJECT_VALUE = 31;

  /**
   * The '<em><b>EString</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EString</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ESTRING
   * @model name="eString" literal="EString"
   * @generated
   * @ordered
   */
  public static final int ESTRING_VALUE = 32;

  /**
   * An array of all the '<em><b>Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Type[] VALUES_ARRAY =
    new Type[]
    {
      EBIG_DECIMAL,
      EBIG_INTEGER,
      EBOOLEAN,
      EBOOLEAN_OBJECT,
      EBYTE,
      EBYTE_ARRAY,
      EBYTE_OBJECT,
      ECHAR,
      ECHARACTER_OBJECT,
      EDATE,
      EDIAGNOSTIC_CHAIN,
      EDOUBLE,
      EDOUBLE_OBJECT,
      EE_LIST,
      EENUMERATOR,
      EFEATURE_MAP,
      EFEATURE_MAP_ENTRY,
      EFLOAT,
      EFLOAT_OBJECT,
      EINT,
      EINTEGER_OBJECT,
      ETREE_ITERATOR,
      EINVOCATION_TARGET_EXCEPTION,
      EJAVA_CLASS,
      EJAVA_OBJECT,
      ELONG,
      ELONG_OBJECT,
      EMAP,
      ERESOURCE,
      ERESOURCE_SET,
      ESHORT,
      ESHORT_OBJECT,
      ESTRING,
    };

  /**
   * A public read-only list of all the '<em><b>Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Type> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Type get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Type result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Type getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Type result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Type get(int value)
  {
    switch (value)
    {
      case EBIG_DECIMAL_VALUE: return EBIG_DECIMAL;
      case EBIG_INTEGER_VALUE: return EBIG_INTEGER;
      case EBOOLEAN_VALUE: return EBOOLEAN;
      case EBOOLEAN_OBJECT_VALUE: return EBOOLEAN_OBJECT;
      case EBYTE_VALUE: return EBYTE;
      case EBYTE_ARRAY_VALUE: return EBYTE_ARRAY;
      case EBYTE_OBJECT_VALUE: return EBYTE_OBJECT;
      case ECHAR_VALUE: return ECHAR;
      case ECHARACTER_OBJECT_VALUE: return ECHARACTER_OBJECT;
      case EDATE_VALUE: return EDATE;
      case EDIAGNOSTIC_CHAIN_VALUE: return EDIAGNOSTIC_CHAIN;
      case EDOUBLE_VALUE: return EDOUBLE;
      case EDOUBLE_OBJECT_VALUE: return EDOUBLE_OBJECT;
      case EE_LIST_VALUE: return EE_LIST;
      case EENUMERATOR_VALUE: return EENUMERATOR;
      case EFEATURE_MAP_VALUE: return EFEATURE_MAP;
      case EFEATURE_MAP_ENTRY_VALUE: return EFEATURE_MAP_ENTRY;
      case EFLOAT_VALUE: return EFLOAT;
      case EFLOAT_OBJECT_VALUE: return EFLOAT_OBJECT;
      case EINT_VALUE: return EINT;
      case EINTEGER_OBJECT_VALUE: return EINTEGER_OBJECT;
      case ETREE_ITERATOR_VALUE: return ETREE_ITERATOR;
      case EINVOCATION_TARGET_EXCEPTION_VALUE: return EINVOCATION_TARGET_EXCEPTION;
      case EJAVA_CLASS_VALUE: return EJAVA_CLASS;
      case EJAVA_OBJECT_VALUE: return EJAVA_OBJECT;
      case ELONG_VALUE: return ELONG;
      case ELONG_OBJECT_VALUE: return ELONG_OBJECT;
      case EMAP_VALUE: return EMAP;
      case ERESOURCE_VALUE: return ERESOURCE;
      case ERESOURCE_SET_VALUE: return ERESOURCE_SET;
      case ESHORT_VALUE: return ESHORT;
      case ESHORT_OBJECT_VALUE: return ESHORT_OBJECT;
      case ESTRING_VALUE: return ESTRING;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Type(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Type
