/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.henshin_text;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unit Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.emf.henshin.text.henshin_text.UnitElement#getSubSequence <em>Sub Sequence</em>}</li>
 * </ul>
 *
 * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getUnitElement()
 * @model
 * @generated
 */
public interface UnitElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Sub Sequence</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.henshin.text.henshin_text.UnitElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sub Sequence</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Sequence</em>' containment reference list.
   * @see org.eclipse.emf.henshin.text.henshin_text.Henshin_textPackage#getUnitElement_SubSequence()
   * @model containment="true"
   * @generated
   */
  EList<UnitElement> getSubSequence();

} // UnitElement
