/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.emf.henshin.text.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.emf.henshin.text.parser.antlr.internal.InternalHenshin_textParser;
import org.eclipse.emf.henshin.text.services.Henshin_textGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class Henshin_textParser extends AbstractAntlrParser {

	@Inject
	private Henshin_textGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHenshin_textParser createParser(XtextTokenStream stream) {
		return new InternalHenshin_textParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public Henshin_textGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Henshin_textGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
